pipeline:
  name: Build golang-arm64
  identifier: Build_golang_arm64_1687071661218
  projectIdentifier: DB
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesHosted
            spec:
              identifier: k8s-hosted-infra
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    connectorRef: account.harnessImage
                    image: alpine
                    shell: Sh
                    command: echo "Welcome to Harness CI"
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1686430062727
        repoName: yjagdale/golang-arm64
        build: <+input>
