name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Install cross-compilers
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu
          sudo apt-get install -y gcc-mingw-w64-x86-64
          sudo apt-get install -y xz-utils

      - name: Checkout code
        uses: actions/checkout@v3

      - name: build go
        run: |
            go version
            go  mod tidy && go mod download && go mod vendor
            CC=aarch64-linux-gnu-gcc CGO_ENABLED=1 go build -o rule-engine .
